### ISSUE TITLE
Fork me on Github is broken

### ISSUE THREAD

**Issue by sdelamo** [dsl-builders/spreadsheet#19]
<img width="1965" alt="Screenshot 2020-11-23 at 15 27 06" src="https://user-images.githubusercontent.com/864788/99973821-7a9c1a00-2da0-11eb-8694-bc8b97e581c9.png">

**Comment by musketyr** [comment]
thank you @sdelamo! I hope I will find a bit of time soon to figure out what's wrong with this one
