### ISSUE TITLE
SpreadsheetBuilder: build methods with template parameter disappeared

### ISSUE THREAD

**Issue by asaremba** [dsl-builders/spreadsheet#2]
In the old Groovy Spreadsheet Builder project, the SpreadsheetBuilder interface had not one but three build methods, two of them containing a template parameter. The documentation still mentions this ("You can pass an existing spreadsheet file as a template as the very first argument of the build method."), but in fact these methods have disappeared since version 1.0.
My proposal is not to adapt the documentation but to revive the methods in the code; I found it useful to be able to provide an Excel template file.

**Comment by musketyr** [comment]
the methods are still there but the docs are wrong

https://github.com/dsl-builders/spreadsheet/blob/master/spreadsheet-builder-poi/src/main/java/builders/dsl/spreadsheet/builder/poi/PoiSpreadsheetBuilder.java#L25

**Comment by asaremba** [comment]
After looking into the source code, I noticed that the template parameter is now available in the create method. As a consequence, I now propose to just update the documentation.
Additional suggestion: A subproject with a few (executable) examples would be helpful for the beginner (and more easily accessible than those that can be found in the Spock tests).
