### ISSUE TITLE
Add support for LocalDate, LocalDateTime & LocalTime

### ISSUE THREAD

**Issue by Krustie101** [dsl-builders/spreadsheet#20]
Currently LocalDate, LocalDateTime & LocalTime are written to the excel sheet via toString, but it makes more sense to write them to excel in the same way as Date / Calendar are written, i.e. as a numeric. As a workaround you can convert them to Date / Calendar but this is so < Java 8.

Similarly, it should be possible to 
- read values as LocalDateTime, LocalDate & LocalTime
- query cell on LocalDateTime, LocalDate & LocalTime

**Comment by musketyr** [comment]
thanks for the PR

**Comment by Krustie101** [comment]
You're welcome. Thank you for all the work you and your colleagues have put into creating this nice library.
