### ISSUE TITLE
Feature Request: [POI] Expose Workbook as output from builder instead of File/IO

### ISSUE THREAD

**Issue by aringeri** [dsl-builders/spreadsheet#24]
Hello,
I really like this DSL, it's a neat and concise way of writing a spreadsheet in JVM langauges.

I have experimented with the `spreadsheet-builder-poi` implementation (in java) and it would suit my use case to get a `Workbook` instance from the `PoiSpreadsheetBuilder` instead of writing the results into a File or IO stream (via side effects).

I would like to use this library as a way of building/structuring a spreadsheet, but not couple it to the IO operation.

Cheers!

**Comment by musketyr** [comment]
Hi, thank you for using the DSL. Do you think that something like #25 would satisfy your needs?

**Comment by aringeri** [comment]
Yes, that would suit my use case. Thank you!

I have another question though, I've noticed that the `PoiWorkbookDefinition` does not support `HSSFWorkbook`s. Do you know why this is? Is there some incompatibility with the older xls HSSFWorkbooks?

**Comment by musketyr** [comment]
If you take a look into the internals in `builders.dsl.spreadsheet.builder.poi` - you cannot only work with the interfaces as you are creating a new objects. Some of the features are not supported by the old format (can't remember which ones from the top of my head) so the decision was made just to support the latest format.

**Comment by aringeri** [comment]
That makes sense. Thanks for all your help @musketyr

**Comment by musketyr** [comment]
Sure thing. I'm glad you found this library useful. Fixed in #25
