### ISSUE TITLE
Bug: Automatic filters and cell width

### ISSUE THREAD

**Issue by mladen-stankovic** [dsl-builders/spreadsheet#3]
Hi,

first of all thank you for this library, you've done a great job!
I would like to report a minor bug: when using automatic filters cell width is not calculated properly (see screenshot)
![screenshot_2](https://user-images.githubusercontent.com/9135786/33128729-b586e934-cf8d-11e7-9bde-7603c890fea0.png)

Seems like cell width is calculated before applying filters so the arrow is displayed over the text

**Comment by musketyr** [comment]
thank you! I've just released version `1.0.2` which should fix this issue

**Comment by mladen-stankovic** [comment]
The fix works perfectly!

Thank you very much for a quick response and a new version.
I will definitely recommend this spreadsheet builder :)

**Comment by musketyr** [comment]
Thank you too

Dne pá 24. 11. 2017 13:26 uživatel Mladen Stankovic <
notifications@github.com> napsal:
