### ISSUE TITLE
Bug: Auto width exception when more than 255 characters in cell

### ISSUE THREAD

**Issue by ulero** [dsl-builders/spreadsheet#5]
Hello!
There seems to be one more bug regarding cell auto width that occurred after implementation of https://github.com/dsl-builders/spreadsheet/issues/3 .  The bug occurs when applying auto width on cell that contains more than 255 characters. Here's the stacktrace:

> java.lang.IllegalArgumentException: The maximum column width for an individual cell is 255 characters.
	org.apache.poi.xssf.usermodel.XSSFSheet.setColumnWidth(XSSFSheet.java:2386)
	builders.dsl.spreadsheet.builder.poi.PoiSheetDefinition.processAutoColumns(PoiSheetDefinition.java:97)
	builders.dsl.spreadsheet.impl.AbstractSheetDefinition.resolve(AbstractSheetDefinition.java:178)
	builders.dsl.spreadsheet.impl.AbstractWorkbookDefinition.sheet(AbstractWorkbookDefinition.java:63)

It seems setColumnWidth instead of autoSizeColumn has been used.

Cheers and keep up the good work, this is great library helping us with generation of XLS files.

**Comment by musketyr** [comment]
Thanks, I'll take look on this problem when I have a bit of time.

Dne pá 15. 12. 2017 11:24 uživatel ulero <notifications@github.com> napsal:

**Comment by musketyr** [comment]
fixed in `1.0.3`
