### ISSUE TITLE
Building a war fails to compile groovy dsl

### ISSUE THREAD

**Issue by iimpulse** [dsl-builders/spreadsheet#9]
Given this might give this repo some traction.

 http://guides.grails.org/grails-file-download-excel/guide/index.html

After building a war for my web application and deploying to a server. 

The application fails with Groovy.lang missing method signature for sheet()

<img width="471" alt="screen shot 2019-01-10 at 6 15 38 pm" src="https://user-images.githubusercontent.com/7397665/51003182-c4a8e900-1503-11e9-8f6b-c83361768e4b.png">

I have fixed this with 

<img width="420" alt="screen shot 2019-01-10 at 6 21 10 pm" src="https://user-images.githubusercontent.com/7397665/51003451-d8a11a80-1504-11e9-9b71-4cb844f36d47.png">

However the groovy support should really account for this ( I think).

**Comment by musketyr** [comment]
Thanks! Can you try to upgrade to `2.0.0.RC1`?

**Comment by musketyr** [comment]
I've tried the guide using 2.0.0.RC1 version and it is fixed there so I'm closing this issue

**Comment by iimpulse** [comment]
@musketyr The guide doesn't build a war and deploy to a server. However I can confirm that in 2.x the expected functionality is working. I will wait for a release to maven. Thanks!

**Comment by musketyr** [comment]
hi, the guide should be updated by @sdelamo. 

`2.0.0.RC1` is already present in `JCenter` repository:

see https://bintray.com/dsl-builders/maven/spreadsheet-builder-poi/2.0.0.RC1

No plans to release to Maven Central at the moment as for the rest of the libraries.

the final `2.0.0` to be released soon I got some bandwidth to merge some outgoing documentation branches.
